export const  ADD_CART_ITEM="ADD_CART_ITEM";
export const DELETE_CART_ITEM="DELETE_CART_ITEM";
export const  INCREASE_ITEM_QUANTITY="INCREASE_ITEM_QUANTITY";
export const DECREASE_ITEM_QUANTITY="DECREASE_ITEM_QUANTITY";
export const GET_TOTAL_ITEM_PRICE="GET_TOTAL_ITEM_PRICE";