export const PRODUCT_LOADING="PRODUCT_LOADING";
export const PRODUCT_ERROR="PRODUCT_ERROR";
export const PRODUCT_SUCESS="PRODUCT_SUCESS";
export const PRODUCT_FILTER="PRODUCT_FILTER";
export const PRODUCT_SEARCH="PRODUCT_SEARCH";

export const SINGLE="SINGLE"